image: node:16.17.0-alpine

stages:
  - test
  - deploy

test-job:
  stage: test
  variables:

  script:
    - npm run lint

dev-deploy:
  stage: deploy
  variables:

  dependencies: []
  environment:
    name: dev
  when: manual
  only:
    - main
    - merge_requests
  script:

staging-deploy:
  stage: deploy
  variables:

  dependencies: []
  environment:
    name: staging
  when: manual
  only:
    - tags
  script:

production-deploy:
  stage: deploy
  variables:

  environment:
    name: production

  script:
