image: node:16.17.0-alpine

stages:
  - test
test-job:
  stage: test
  variables:

  script:
    - npm run lint

  dependencies: []
  environment:
    name: dev
  when: manual
  only:
    - main
    - merge_requests
